"use server";
import { AuthError } from "next-auth";
import { signIn } from "@/auth";
import { redirect } from "next/dist/server/api-utils";

export async function authenticate(
  prevState: string | undefined,
  formData: FormData
) {
  try {
    await signIn("credentials", {
      ...Object.fromEntries(formData),
      redirect: false,
    });

    return "Success";
  } catch (error) {
    if (error instanceof AuthError) {
      switch (error.type) {
        case "CredentialsSignin":
          return "Invalid credentials.";
        default:
          return "Something went wrong.";
      }
    }
    throw error;
  }
}

export async function login(email: string, password: string) {
  try {
    await signIn("credentials", { email, password, redirect: false });
  } catch (error) {
    console.log(error);
    return {
      ok: false,
      message: "No se pudo iniciar sesi√≥n",
    };
  }
}
